# Step 1: Use official JDK image
FROM openjdk:17-jdk-slim

# Step 2: Set working directory inside container
WORKDIR /app

# Step 3: Copy your Spring Boot JAR into the container
COPY target/employee-management-0.0.1-SNAPSHOT.jar app.jar

# Step 4: Run the JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
